CREATE TABLE COMUNA (
    Id INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE PANTILLA_CURSO (
    Id INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE APODERADO (
    Id INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    esProgenitor BOOLEAN NOT NULL
);

CREATE TABLE COLEGIO (
    Id INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    IdComuna INT NOT NULL,
    FOREIGN KEY (IdComuna) REFERENCES COMUNA(Id)
);

CREATE TABLE EMPLEADO (
    Id INT PRIMARY KEY,
    IdSueldo INT,
    IdColegio INT NOT NULL,
    IdProfesor INT,
    Nombre VARCHAR(100) NOT NULL,
    Rol VARCHAR(100) NOT NULL,
    FOREIGN KEY (IdColegio) REFERENCES COLEGIO(Id)
);

CREATE TABLE SUELDO (
    Id INT PRIMARY KEY,
    IdEmpleado INT NOT NULL,
    Cantidad INT NOT NULL,
    FOREIGN KEY (IdEmpleado) REFERENCES EMPLEADO(Id)
);

ALTER TABLE EMPLEADO
ADD CONSTRAINT fk_empleado_sueldo
FOREIGN KEY (IdSueldo) REFERENCES SUELDO(Id);

CREATE TABLE PROFESOR (
    Id INT PRIMARY KEY,
    IdEmpleado INT NOT NULL,
    Especializacion VARCHAR(100),
    FOREIGN KEY (IdEmpleado) REFERENCES EMPLEADO(Id)
);

ALTER TABLE EMPLEADO
ADD COLUMN IdComuna INT NOT NULL;

ALTER TABLE EMPLEADO
ADD CONSTRAINT fk_empleado_comuna
FOREIGN KEY (IdComuna) REFERENCES COMUNA(Id);

CREATE TABLE CURSO (
    Id INT PRIMARY KEY,
    IdPantillaCurso INT NOT NULL,
    Anio INT NOT NULL,
    FOREIGN KEY (IdPantillaCurso) REFERENCES PANTILLA_CURSO(Id)
);

CREATE TABLE PROF_CURSO (
    Id INT PRIMARY KEY,
    IdProfesor INT NOT NULL,
    IdCurso INT NOT NULL,
    esJefe BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (IdProfesor) REFERENCES PROFESOR(Id),
    FOREIGN KEY (IdCurso) REFERENCES CURSO(Id)
);

CREATE TABLE FRANJA_HORARIA (
    Id INT PRIMARY KEY,
    IdProfCurso INT NOT NULL,
    Dia VARCHAR(20) NOT NULL,
    Anio INT NOT NULL,
    HoraInicio VARCHAR(10) NOT NULL,
    FOREIGN KEY (IdProfCurso) REFERENCES PROF_CURSO(Id)
);

CREATE TABLE ALUMNO (
    Id INT PRIMARY KEY,
    IdAlumno INT NOT NULL,
    IdComuna INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Rut VARCHAR(20) NOT NULL,
    IdApoderado INT NOT NULL,
    FOREIGN KEY (IdComuna) REFERENCES COMUNA(Id),
    FOREIGN KEY (IdApoderado) REFERENCES APODERADO(Id)
);

CREATE TABLE ALU_CURSO (
    Id INT PRIMARY KEY,
    IdCurso INT NOT NULL,
    IdAlumno INT NOT NULL,
    FOREIGN KEY (IdCurso) REFERENCES CURSO(Id),
    FOREIGN KEY (IdAlumno) REFERENCES ALUMNO(Id)
);

CREATE TABLE ASISTENCIA (
    Id INT PRIMARY KEY,
    IdAluCurso INT NOT NULL,
    IdFranjaHoraria INT NOT NULL,
    Fecha DATE NOT NULL,
    FOREIGN KEY (IdAluCurso) REFERENCES ALU_CURSO(Id),
    FOREIGN KEY (IdFranjaHoraria) REFERENCES FRANJA_HORARIA(Id)
);