-- dbCreate.sql - Creación de tablas
-- 1. COMUNA
CREATE TABLE COMUNA (
    Id INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

-- 2. PANTILLA_CURSO
CREATE TABLE PANTILLA_CURSO (
    Id INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

-- 3. APODERADO
CREATE TABLE APODERADO (
    Id INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    esProgenitor BOOLEAN NOT NULL
);

-- 4. COLEGIO (necesita COMUNA)
CREATE TABLE COLEGIO (
    Id INT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    IdComuna INT NOT NULL,
    FOREIGN KEY (IdComuna) REFERENCES COMUNA(Id)
);

-- 5. EMPLEADO (sin FK de SUELDO y PROFESOR por problema circular)
--    IdComuna: comuna de residencia del empleado
CREATE TABLE EMPLEADO (
    Id INT PRIMARY KEY,
    IdSueldo INT,
    IdColegio INT NOT NULL,
    IdProfesor INT,
    IdComuna INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Rol VARCHAR(100) NOT NULL,
    FOREIGN KEY (IdColegio) REFERENCES COLEGIO(Id),
    FOREIGN KEY (IdComuna) REFERENCES COMUNA(Id)
);

-- 6. SUELDO (necesita EMPLEADO)
CREATE TABLE SUELDO (
    Id INT PRIMARY KEY,
    IdEmpleado INT NOT NULL,
    Cantidad INT NOT NULL,
    FOREIGN KEY (IdEmpleado) REFERENCES EMPLEADO(Id)
);

-- 7. FK de SUELDO en EMPLEADO (resuelve circular)
ALTER TABLE EMPLEADO
ADD CONSTRAINT fk_empleado_sueldo
FOREIGN KEY (IdSueldo) REFERENCES SUELDO(Id);

-- 8. PROFESOR (necesita EMPLEADO)
CREATE TABLE PROFESOR (
    Id INT PRIMARY KEY,
    IdEmpleado INT NOT NULL,
    Especializacion VARCHAR(100),
    FOREIGN KEY (IdEmpleado) REFERENCES EMPLEADO(Id)
);

-- 9. FK de PROFESOR en EMPLEADO (resuelve circular)
ALTER TABLE EMPLEADO
ADD CONSTRAINT fk_empleado_profesor
FOREIGN KEY (IdProfesor) REFERENCES PROFESOR(Id);

-- 10. CURSO (necesita PANTILLA_CURSO)
CREATE TABLE CURSO (
    Id INT PRIMARY KEY,
    IdPantillaCurso INT NOT NULL,
    Anio INT NOT NULL,
    FOREIGN KEY (IdPantillaCurso) REFERENCES PANTILLA_CURSO(Id)
);

-- 11. PROF_CURSO (necesita PROFESOR y CURSO)
CREATE TABLE PROF_CURSO (
    Id INT PRIMARY KEY,
    IdProfesor INT NOT NULL,
    IdCurso INT NOT NULL,
    esJefe BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (IdProfesor) REFERENCES PROFESOR(Id),
    FOREIGN KEY (IdCurso) REFERENCES CURSO(Id)
);

-- 12. FRANJA_HORARIA (necesita PROF_CURSO)
CREATE TABLE FRANJA_HORARIA (
    Id INT PRIMARY KEY,
    IdProfCurso INT NOT NULL,
    Dia VARCHAR(20) NOT NULL,
    Anio INT NOT NULL,
    HoraInicio VARCHAR(10) NOT NULL,
    FOREIGN KEY (IdProfCurso) REFERENCES PROF_CURSO(Id)
);

-- 13. ALUMNO (necesita COMUNA y APODERADO)
CREATE TABLE ALUMNO (
    Id INT PRIMARY KEY,
    IdAlumno INT NOT NULL,
    IdComuna INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Rut VARCHAR(20) NOT NULL,
    IdApoderado INT NOT NULL,
    FOREIGN KEY (IdComuna) REFERENCES COMUNA(Id),
    FOREIGN KEY (IdApoderado) REFERENCES APODERADO(Id)
);

-- 14. ALU_CURSO (necesita CURSO y ALUMNO)
CREATE TABLE ALU_CURSO (
    Id INT PRIMARY KEY,
    IdCurso INT NOT NULL,
    IdAlumno INT NOT NULL,
    FOREIGN KEY (IdCurso) REFERENCES CURSO(Id),
    FOREIGN KEY (IdAlumno) REFERENCES ALUMNO(Id)
);

-- 15. ASISTENCIA (necesita ALU_CURSO y FRANJA_HORARIA)
CREATE TABLE ASISTENCIA (
    Id INT PRIMARY KEY,
    IdAluCurso INT NOT NULL,
    IdFranjaHoraria INT NOT NULL,
    Fecha DATE NOT NULL,
    FOREIGN KEY (IdAluCurso) REFERENCES ALU_CURSO(Id),
    FOREIGN KEY (IdFranjaHoraria) REFERENCES FRANJA_HORARIA(Id)
);