INSERT INTO COMUNA VALUES (1, 'Santiago');
INSERT INTO COMUNA VALUES (2, 'Providencia');
INSERT INTO COMUNA VALUES (3, 'Maipú');
INSERT INTO COMUNA VALUES (4, 'Las Condes');
INSERT INTO COMUNA VALUES (5, 'La Florida');

INSERT INTO PANTILLA_CURSO VALUES (1, '1 Basico');
INSERT INTO PANTILLA_CURSO VALUES (2, '2 Basico');
INSERT INTO PANTILLA_CURSO VALUES (3, '3 Basico');
INSERT INTO PANTILLA_CURSO VALUES (4, '1 Medio');

INSERT INTO APODERADO VALUES (1, 'Juan Perez', TRUE);
INSERT INTO APODERADO VALUES (2, 'Maria Gonzalez', TRUE);
INSERT INTO APODERADO VALUES (3, 'Carlos Munoz', FALSE);
INSERT INTO APODERADO VALUES (4, 'Ana Lopez', TRUE);
INSERT INTO APODERADO VALUES (5, 'Roberto Soto', FALSE);

INSERT INTO COLEGIO VALUES (1, 'Colegio San Marcos', 1);
INSERT INTO COLEGIO VALUES (2, 'Colegio Santa Maria', 2);
INSERT INTO COLEGIO VALUES (3, 'Liceo Bicentenario', 3);

INSERT INTO EMPLEADO (Id, IdSueldo, IdColegio, IdProfesor, IdComuna, Nombre, Rol)
VALUES (1, NULL, 1, NULL, 1, 'Pedro Alvarez', 'Profesor');
INSERT INTO EMPLEADO (Id, IdSueldo, IdColegio, IdProfesor, IdComuna, Nombre, Rol)
VALUES (2, NULL, 1, NULL, 2, 'Laura Vega', 'Profesor');
INSERT INTO EMPLEADO (Id, IdSueldo, IdColegio, IdProfesor, IdComuna, Nombre, Rol)
VALUES (3, NULL, 2, NULL, 3, 'Mario Rojas', 'Profesor');
INSERT INTO EMPLEADO (Id, IdSueldo, IdColegio, IdProfesor, IdComuna, Nombre, Rol)
VALUES (4, NULL, 2, NULL, 1, 'Claudia Mora', 'Profesor');
INSERT INTO EMPLEADO (Id, IdSueldo, IdColegio, IdProfesor, IdComuna, Nombre, Rol)
VALUES (5, NULL, 3, NULL, 4, 'Felipe Castro', 'Profesor');
INSERT INTO EMPLEADO (Id, IdSueldo, IdColegio, IdProfesor, IdComuna, Nombre, Rol)
VALUES (6, NULL, 1, NULL, 5, 'Rosa Fuentes', 'Administrativo');

INSERT INTO SUELDO VALUES (1, 1, 850000);
INSERT INTO SUELDO VALUES (2, 2, 920000);
INSERT INTO SUELDO VALUES (3, 3, 780000);
INSERT INTO SUELDO VALUES (4, 4, 860000);
INSERT INTO SUELDO VALUES (5, 5, 950000);
INSERT INTO SUELDO VALUES (6, 6, 700000);

UPDATE EMPLEADO SET IdSueldo = 1 WHERE Id = 1;
UPDATE EMPLEADO SET IdSueldo = 2 WHERE Id = 2;
UPDATE EMPLEADO SET IdSueldo = 3 WHERE Id = 3;
UPDATE EMPLEADO SET IdSueldo = 4 WHERE Id = 4;
UPDATE EMPLEADO SET IdSueldo = 5 WHERE Id = 5;
UPDATE EMPLEADO SET IdSueldo = 6 WHERE Id = 6;

INSERT INTO PROFESOR VALUES (1, 1, 'Matematicas');
INSERT INTO PROFESOR VALUES (2, 2, 'Lenguaje');
INSERT INTO PROFESOR VALUES (3, 3, 'Ciencias');
INSERT INTO PROFESOR VALUES (4, 4, 'Historia');
INSERT INTO PROFESOR VALUES (5, 5, 'Educacion Fisica');

UPDATE EMPLEADO SET IdProfesor = 1 WHERE Id = 1;
UPDATE EMPLEADO SET IdProfesor = 2 WHERE Id = 2;
UPDATE EMPLEADO SET IdProfesor = 3 WHERE Id = 3;
UPDATE EMPLEADO SET IdProfesor = 4 WHERE Id = 4;
UPDATE EMPLEADO SET IdProfesor = 5 WHERE Id = 5;

INSERT INTO CURSO VALUES (1, 1, 2019);
INSERT INTO CURSO VALUES (2, 2, 2019);
INSERT INTO CURSO VALUES (3, 3, 2019);
INSERT INTO CURSO VALUES (4, 1, 2020);
INSERT INTO CURSO VALUES (5, 2, 2020);
INSERT INTO CURSO VALUES (6, 4, 2021);
INSERT INTO PROF_CURSO VALUES (1, 1, 1, TRUE);
INSERT INTO PROF_CURSO VALUES (2, 2, 1, FALSE);
INSERT INTO PROF_CURSO VALUES (3, 3, 2, TRUE);
INSERT INTO PROF_CURSO VALUES (4, 4, 3, TRUE);
INSERT INTO PROF_CURSO VALUES (5, 5, 4, TRUE);
INSERT INTO PROF_CURSO VALUES (6, 1, 5, FALSE);
INSERT INTO FRANJA_HORARIA VALUES (1, 1, 'Lunes',     2019, '08:00');
INSERT INTO FRANJA_HORARIA VALUES (2, 1, 'Martes',    2019, '09:00');
INSERT INTO FRANJA_HORARIA VALUES (3, 2, 'Miercoles', 2019, '10:00');
INSERT INTO FRANJA_HORARIA VALUES (4, 3, 'Jueves',    2019, '08:00');
INSERT INTO FRANJA_HORARIA VALUES (5, 4, 'Viernes',   2019, '11:00');
INSERT INTO FRANJA_HORARIA VALUES (6, 5, 'Lunes',     2020, '08:00');
INSERT INTO ALUMNO VALUES (1, 1, 1, 'Diego Ramirez',   '12.345.678-9', 1);
INSERT INTO ALUMNO VALUES (2, 2, 2, 'Sofia Torres',    '13.456.789-0', 2);
INSERT INTO ALUMNO VALUES (3, 3, 1, 'Matias Silva',    '14.567.890-1', 3);
INSERT INTO ALUMNO VALUES (4, 4, 3, 'Valentina Diaz',  '15.678.901-2', 4);
INSERT INTO ALUMNO VALUES (5, 5, 2, 'Sebastian Reyes', '16.789.012-3', 5);
INSERT INTO ALUMNO VALUES (6, 6, 1, 'Camila Ortiz',    '17.890.123-4', 1);

INSERT INTO ALU_CURSO VALUES (1, 1, 1);
INSERT INTO ALU_CURSO VALUES (2, 1, 2);
INSERT INTO ALU_CURSO VALUES (3, 2, 3);
INSERT INTO ALU_CURSO VALUES (4, 2, 4);
INSERT INTO ALU_CURSO VALUES (5, 3, 5);
INSERT INTO ALU_CURSO VALUES (6, 3, 6);
INSERT INTO ALU_CURSO VALUES (7, 4, 1);
INSERT INTO ALU_CURSO VALUES (8, 5, 2);
INSERT INTO ALU_CURSO VALUES (9, 6, 3);

INSERT INTO ASISTENCIA VALUES (1, 1, 1, '2019-03-04');
INSERT INTO ASISTENCIA VALUES (2, 1, 2, '2019-03-05');
INSERT INTO ASISTENCIA VALUES (3, 2, 1, '2019-03-04');
INSERT INTO ASISTENCIA VALUES (4, 3, 3, '2019-03-06');
INSERT INTO ASISTENCIA VALUES (5, 4, 4, '2019-03-07');
INSERT INTO ASISTENCIA VALUES (6, 5, 5, '2019-03-08');
INSERT INTO ASISTENCIA VALUES (7, 2, 2, '2019-04-01');
INSERT INTO ASISTENCIA VALUES (8, 3, 3, '2019-04-02');
INSERT INTO ASISTENCIA VALUES (9, 6, 5, '2019-05-01');
